/**
 * loadAllTools — the single entry point for generating the complete tool
 * registry from schema. Combines:
 *   1. Intent tools (from intents/*.yaml) → apiSurface.executeIntent
 *   2. Entity CRUD tools (from entities/*.yaml) → apiSurface.queryEntities/mutateEntity
 *   3. Built-in interaction tools (SDK-owned, generic)
 *
 * This replaces hand-authored tool definitions entirely. The host provides
 * schemas (generated by introspection) + an apiSurface binding; the SDK
 * generates every tool.
 *
 * @see docs/reference/integration-contract.md §4
 */
import { loadToolsFromSchema } from './schema-loader.js';
import { loadEntityToolsFromSchema } from './entity-tools.js';
import { loadBuiltinTools } from './builtin-tools.js';
import type { RegisteredTool } from './types.js';
import type { LoadToolsOptions } from './schema-loader.js';

export interface LoadAllToolsOptions extends LoadToolsOptions {
  /** Path to the schema directory (e.g. ./schemas/my-app/) */
  schemasDir: string;
}

/**
 * Generate the complete tool registry from schema + built-ins.
 * This is the only tool-loading function a host worker should call.
 */
export async function loadAllTools(options: LoadAllToolsOptions): Promise<RegisteredTool[]> {
  const [intentTools, entityTools] = await Promise.all([
    loadToolsFromSchema(options.schemasDir, {
      ...(options.events ? { events: options.events } : {}),
      ...(options.waiter ? { waiter: options.waiter } : {}),
    }),
    loadEntityToolsFromSchema(options.schemasDir),
  ]);

  const builtinTools = loadBuiltinTools();

  // Merge, deduping by name (entity CRUD may overlap with intent tools for
  // entities that also have explicit intents like create-character)
  const seen = new Set<string>();
  const all: RegisteredTool[] = [];
  for (const tool of [...intentTools, ...entityTools, ...builtinTools]) {
    if (!seen.has(tool.name)) {
      seen.add(tool.name);
      all.push(tool);
    }
  }

  return all;
}
